export interface Country {
  name: string;
  code: string;
  currencySymbol: string;
  callingCode: string;
}

export const countries: Country[] = [
  { name: 'India', code: 'IN', currencySymbol: '₹', callingCode: '+91' },
  { name: 'United States', code: 'US', currencySymbol: '$', callingCode: '+1' },
  { name: 'United Kingdom', code: 'GB', currencySymbol: '£', callingCode: '+44' },
  { name: 'Canada', code: 'CA', currencySymbol: 'C$', callingCode: '+1' },
  { name: 'Australia', code: 'AU', currencySymbol: 'A$', callingCode: '+61' },
  { name: 'Germany', code: 'DE', currencySymbol: '€', callingCode: '+49' },
  { name: 'France', code: 'FR', currencySymbol: '€', callingCode: '+33' },
  { name: 'Japan', code: 'JP', currencySymbol: '¥', callingCode: '+81' },
  { name: 'China', code: 'CN', currencySymbol: '¥', callingCode: '+86' },
  { name: 'Brazil', code: 'BR', currencySymbol: 'R$', callingCode: '+55' },
  { name: 'Mexico', code: 'MX', currencySymbol: '$', callingCode: '+52' },
  { name: 'United Arab Emirates', code: 'AE', currencySymbol: 'د.إ', callingCode: '+971' },
  { name: 'Saudi Arabia', code: 'SA', currencySymbol: 'SAR', callingCode: '+966' },
  { name: 'Singapore', code: 'SG', currencySymbol: 'S$', callingCode: '+65' },
  { name: 'Malaysia', code: 'MY', currencySymbol: 'RM', callingCode: '+60' },
  { name: 'Indonesia', code: 'ID', currencySymbol: 'Rp', callingCode: '+62' },
  { name: 'Thailand', code: 'TH', currencySymbol: '฿', callingCode: '+66' },
  { name: 'Vietnam', code: 'VN', currencySymbol: '₫', callingCode: '+84' },
  { name: 'Philippines', code: 'PH', currencySymbol: '₱', callingCode: '+63' },
  { name: 'South Korea', code: 'KR', currencySymbol: '₩', callingCode: '+82' },
  { name: 'Russia', code: 'RU', currencySymbol: '₽', callingCode: '+7' },
  { name: 'South Africa', code: 'ZA', currencySymbol: 'R', callingCode: '+27' },
  { name: 'Nigeria', code: 'NG', currencySymbol: '₦', callingCode: '+234' },
  { name: 'Egypt', code: 'EG', currencySymbol: '£', callingCode: '+20' },
  { name: 'Netherlands', code: 'NL', currencySymbol: '€', callingCode: '+31' },
  { name: 'Belgium', code: 'BE', currencySymbol: '€', callingCode: '+32' },
  { name: 'Switzerland', code: 'CH', currencySymbol: 'CHF', callingCode: '+41' },
  { name: 'Austria', code: 'AT', currencySymbol: '€', callingCode: '+43' },
  { name: 'Sweden', code: 'SE', currencySymbol: 'kr', callingCode: '+46' },
  { name: 'Norway', code: 'NO', currencySymbol: 'kr', callingCode: '+47' },
  { name: 'Denmark', code: 'DK', currencySymbol: 'kr', callingCode: '+45' },
  { name: 'Finland', code: 'FI', currencySymbol: '€', callingCode: '+358' },
  { name: 'Poland', code: 'PL', currencySymbol: 'zł', callingCode: '+48' },
  { name: 'Czech Republic', code: 'CZ', currencySymbol: 'Kč', callingCode: '+420' },
  { name: 'Portugal', code: 'PT', currencySymbol: '€', callingCode: '+351' },
  { name: 'Spain', code: 'ES', currencySymbol: '€', callingCode: '+34' },
  { name: 'Italy', code: 'IT', currencySymbol: '€', callingCode: '+39' },
  { name: 'Greece', code: 'GR', currencySymbol: '€', callingCode: '+30' },
  { name: 'Turkey', code: 'TR', currencySymbol: '₺', callingCode: '+90' },
  { name: 'Israel', code: 'IL', currencySymbol: '₪', callingCode: '+972' },
  { name: 'New Zealand', code: 'NZ', currencySymbol: 'NZ$', callingCode: '+64' },
  { name: 'Ireland', code: 'IE', currencySymbol: '€', callingCode: '+353' },
  { name: 'Pakistan', code: 'PK', currencySymbol: '₨', callingCode: '+92' },
  { name: 'Bangladesh', code: 'BD', currencySymbol: '৳', callingCode: '+880' },
  { name: 'Sri Lanka', code: 'LK', currencySymbol: 'රු', callingCode: '+94' },
  { name: 'Nepal', code: 'NP', currencySymbol: 'रू', callingCode: '+977' },
  { name: 'Bhutan', code: 'BT', currencySymbol: 'Nu.', callingCode: '+975' },
  { name: 'Maldives', code: 'MV', currencySymbol: 'Rf', callingCode: '+960' },
  { name: 'Argentina', code: 'AR', currencySymbol: '$', callingCode: '+54' },
  { name: 'Chile', code: 'CL', currencySymbol: '$', callingCode: '+56' },
  { name: 'Peru', code: 'PE', currencySymbol: 'S/', callingCode: '+51' },
  { name: 'Colombia', code: 'CO', currencySymbol: '$', callingCode: '+57' },
];
