import { useState, useRef, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Send, Bot, User, Sparkles, TrendingUp, Users, Clock, Brain, Zap, Mic, Paperclip, Lightbulb } from 'lucide-react';
import { ChatMessage } from '../lib/types';
import { chatAPI } from '../lib/api';
import { useApp } from '../App';

const suggestions = [
  { icon: TrendingUp, text: 'Show attendance trends this month', color: '#3B82F6' },
  { icon: Users, text: 'Which department has highest absenteeism?', color: '#F97316' },
  { icon: Clock, text: "Predict next week's attendance", color: '#10B981' },
  { icon: Brain, text: 'Generate HR summary report', color: '#8B5CF6' },
];

const aiResponses: Record<string, string> = {
  'Show attendance trends this month': [
    '📊 **Monthly Attendance Analysis:**',
    '',
    '• Overall attendance rate: **93.1%** (up 2.1% from last month)',
    '• Best day: Wednesday (96% attendance)',
    '• Challenging day: Friday (87% attendance)',
    '',
    '**Key Insights:**',
    '- Engineering department leads with 94% attendance',
    '- Late arrivals decreased by 15% compared to December',
    '- Remote work requests increased on Mondays and Fridays',
    '',
    '**Recommendation:** Consider implementing flexible Friday schedules to improve end-of-week attendance.',
  ].join('\n'),
  'Which department has highest absenteeism?': [
    '📈 **Department Absenteeism Report:**',
    '',
    '1. **Finance** - 15% absence rate (concerning)',
    '2. **Sales** - 10% absence rate',
    '3. **Engineering** - 6% absence rate (best performing)',
    '4. **Marketing** - 4% absence rate',
    '5. **HR** - 2% absence rate',
    '',
    '**AI Analysis:**',
    'Finance department shows a pattern of Monday absences. This could indicate burnout or workload issues. I recommend scheduling a wellness check-in with the Finance team.',
    '',
    '**Predicted Impact:** Addressing this could save ~$12,000/month in productivity loss.',
  ].join('\n'),
  "Predict next week's attendance": [
    '🔮 **AI Attendance Prediction for Next Week:**',
    '',
    '• **Monday:** 91% (Expected 3 late arrivals)',
    '• **Tuesday:** 94% (Normal pattern)',
    '• **Wednesday:** 96% (Peak day)',
    '• **Thursday:** 93% (Slight dip expected)',
    '• **Friday:** 88% (Below target)',
    '',
    '**Risk Factors:**',
    '- James Wright likely to be absent (pattern detected)',
    '- Weather alert may affect Tuesday commute',
    '- 2 employees have pending leave requests',
    '',
    '**Suggested Actions:**',
    '1. Send reminder to at-risk employees',
    '2. Prepare remote work options for Tuesday',
    '3. Process pending leave requests proactively',
  ].join('\n'),
  'Generate HR summary report': [
    '📋 **AI-Generated HR Summary - January 2025:**',
    '',
    '**Workforce Overview:**',
    '• Total headcount: 248 (+12 from last month)',
    '• Active: 231 | Remote: 4 | On Leave: 9 | Absent: 4',
    '• Turnover rate: 2.1% (below industry avg of 3.5%)',
    '',
    '**Attendance Metrics:**',
    '• Average attendance: 93.1%',
    '• On-time rate: 89.2%',
    '• Overtime hours: 156h total',
    '',
    '**Performance Highlights:**',
    '• Top performer: David Kim (96% score)',
    '• Most improved: Yuki Tanaka (+8%)',
    '• Team of the month: Engineering',
    '',
    '**Action Items:**',
    '1. 3 performance reviews overdue',
    '2. 7 leave requests pending approval',
    '3. Payroll processing due in 5 days',
    '',
    '*This report was auto-generated by Traxale AI v2.0*',
  ].join('\n'),
};

const defaultResponse = [
  '🤖 I have analyzed your query and here is what I found:',
  '',
  'Based on current data patterns and AI analysis, I can provide detailed insights on attendance, employee performance, HR metrics, and predictive analytics.',
  '',
  '**Quick Stats:**',
  '• Current attendance rate: 93.1%',
  '• Employee satisfaction: 87%',
  '• Pending actions: 12 items',
  '',
  'Would you like me to dive deeper into any specific area? I can help with:',
  '- Attendance analytics',
  '- Performance reviews',
  '- Leave management',
  '- Payroll insights',
  '- Predictive modeling',
].join('\n');

export default function AIAssistant() {
  const { currentUser, setCurrentPage } = useApp();
  const isSuperAdmin = currentUser?.role === 'super_admin';
  
  // Redirect super admin to their dashboard
  useEffect(() => {
    if (isSuperAdmin) {
      setCurrentPage('super-admin-dashboard');
    }
  }, [isSuperAdmin, setCurrentPage]);
  
  if (isSuperAdmin) return null;
  
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      role: 'assistant',
      content: [
        '👋 Hello! I am your **Traxale AI Assistant**.',
        'I can help you with HR analytics, attendance insights, employee reports, and smart recommendations.',
        '',
        'What would you like to know today?',
      ].join('\n'),
      timestamp: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
    },
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const sendMessage = async (text: string) => {
    if (!text.trim()) return;

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: text,
      timestamp: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsTyping(true);

    try {
      const res = await chatAPI.sendMessage({ content: text, channelId: 'default' });
      if (res.success && res.data && res.data.length > 0) {
        const aiMsg: ChatMessage = {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: res.data[1].content,
          timestamp: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        };
        setMessages(prev => [...prev, aiMsg]);
      } else {
        throw new Error('No response from backend');
      }
    } catch (error) {
      // Fallback to local AI responses
      setTimeout(() => {
        const response = aiResponses[text] || defaultResponse;
        const aiMsg: ChatMessage = {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: response,
          timestamp: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        };
        setMessages(prev => [...prev, aiMsg]);
      }, 1500);
    }
    setIsTyping(false);
  };

  const formatContent = (content: string) => {
    return content.split('\n').map((line, i) => {
      let formatted = line
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/•/g, '<span style="color: #3B82F6">•</span>');
      return <p key={i} className="text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: formatted || '&nbsp;' }} />;
    });
  };

  return (
    <div className="flex flex-col h-[calc(100vh-140px)]">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl flex items-center justify-center neon-glow" style={{ background: 'linear-gradient(135deg, #3B82F6, #1D4ED8)' }}>
            <Bot size={24} className="text-white" />
          </div>
          <div>
            <h1 className="text-xl font-bold flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
              AI Assistant <Sparkles size={16} style={{ color: '#F97316' }} />
            </h1>
            <p className="text-xs flex items-center gap-1" style={{ color: 'var(--text-muted)' }}>
              <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" /> Traxale AI v2.0 · Online
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <div className="px-3 py-1.5 rounded-lg text-xs font-medium" style={{ background: 'rgba(59, 130, 246, 0.1)', color: '#3B82F6' }}>
            <Zap size={12} className="inline mr-1" /> Pro Mode
          </div>
        </div>
      </div>

      {/* Chat Area */}
      <div className="flex-1 glass-card rounded-2xl flex flex-col overflow-hidden">
        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {messages.map((msg) => (
            <motion.div
              key={msg.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
            >
              <div className={`w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0 ${msg.role === 'assistant' ? 'neon-glow' : ''}`} style={{
                background: msg.role === 'assistant' ? 'linear-gradient(135deg, #3B82F6, #1D4ED8)' : 'linear-gradient(135deg, #F97316, #EA580C)',
              }}>
                {msg.role === 'assistant' ? <Bot size={16} className="text-white" /> : <User size={16} className="text-white" />}
              </div>

              <div className={`max-w-[75%] ${msg.role === 'user' ? 'chat-bubble-user' : 'chat-bubble'} p-4`} style={{
                background: msg.role === 'user' ? 'linear-gradient(135deg, #3B82F6, #2563EB)' : 'var(--bg-glass)',
                border: msg.role === 'assistant' ? '1px solid var(--border-color)' : 'none',
                color: msg.role === 'user' ? '#fff' : 'var(--text-primary)',
              }}>
                {formatContent(msg.content)}
                <p className="text-[10px] mt-2 opacity-50">{msg.timestamp}</p>
              </div>
            </motion.div>
          ))}

          {isTyping && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex gap-3">
              <div className="w-8 h-8 rounded-xl flex items-center justify-center neon-glow" style={{ background: 'linear-gradient(135deg, #3B82F6, #1D4ED8)' }}>
                <Bot size={16} className="text-white" />
              </div>
              <div className="chat-bubble p-4" style={{ background: 'var(--bg-glass)', border: '1px solid var(--border-color)' }}>
                <div className="flex items-center gap-2">
                  <div className="flex gap-1">
                    <div className="w-2 h-2 rounded-full animate-bounce" style={{ background: '#3B82F6', animationDelay: '0ms' }} />
                    <div className="w-2 h-2 rounded-full animate-bounce" style={{ background: '#3B82F6', animationDelay: '150ms' }} />
                    <div className="w-2 h-2 rounded-full animate-bounce" style={{ background: '#3B82F6', animationDelay: '300ms' }} />
                  </div>
                  <span className="text-xs" style={{ color: 'var(--text-muted)' }}>AI is thinking...</span>
                </div>
              </div>
            </motion.div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Suggestions */}
        {messages.length <= 1 && (
          <div className="px-6 pb-4">
            <p className="text-xs font-medium mb-3 flex items-center gap-1" style={{ color: 'var(--text-muted)' }}>
              <Lightbulb size={12} /> Quick Questions
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {suggestions.map((s, i) => (
                <button
                  key={i}
                  onClick={() => sendMessage(s.text)}
                  className="flex items-center gap-3 p-3 rounded-xl text-left text-sm transition-all hover:scale-[1.02] hover:border-blue-500/30"
                  style={{ background: 'var(--bg-glass)', border: '1px solid var(--border-color)', color: 'var(--text-secondary)' }}
                >
                  <s.icon size={16} style={{ color: s.color }} />
                  {s.text}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Input Area */}
        <div className="p-4 border-t" style={{ borderColor: 'var(--border-color)' }}>
          <div className="flex items-center gap-3">
            <button className="p-2.5 rounded-xl transition-all hover:scale-105" style={{ background: 'var(--bg-glass)', border: '1px solid var(--border-color)', color: 'var(--text-muted)' }}>
              <Paperclip size={18} />
            </button>
            <div className="flex-1 flex items-center gap-2 px-4 py-3 rounded-xl" style={{ background: 'var(--bg-glass)', border: '1px solid var(--border-color)' }}>
              <input
                type="text"
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && sendMessage(input)}
                placeholder="Ask AI anything about your HR data..."
                className="bg-transparent outline-none text-sm flex-1"
                style={{ color: 'var(--text-primary)' }}
              />
              <button className="p-1 rounded-lg transition-all hover:bg-white/10" style={{ color: 'var(--text-muted)' }}>
                <Mic size={16} />
              </button>
            </div>
            <button
              onClick={() => sendMessage(input)}
              disabled={!input.trim()}
              className="p-3 rounded-xl text-white transition-all hover:scale-105 disabled:opacity-50 disabled:hover:scale-100"
              style={{ background: 'linear-gradient(135deg, #3B82F6, #2563EB)' }}
            >
              <Send size={18} />
            </button>
          </div>
          <p className="text-[10px] text-center mt-2" style={{ color: 'var(--text-muted)' }}>
            Traxale AI processes data securely. Your information is encrypted and never shared.
          </p>
        </div>
      </div>
    </div>
  );
}
